### ISSUE TITLE
Missing source files.

### ISSUE THREAD

**Issue by shaobohou** [shaobohou/madios#1]
Stringable.cpp
special.cpp
MiscUtils.cpp

and the corresponding header files are needed for compilation.

**Comment by JohnMe** [comment]
NRMatrix defintions seem to be missing. Would really like to compile this. thanks

**Comment by JohnMe** [comment]
Addition: Are the files you mention the ones from http://code.google.com/p/shaobohou-cppcodes/ ?

**Comment by shaobohou** [comment]
The files from http://code.google.com/p/shaobohou-cppcodes/ are slightly out of date. 

I will put up the relevant files later today.

**Comment by shaobohou** [comment]
The code now compiles and I have added a test file for the corpus shown in the README.

**Comment by JohnMe** [comment]
Can confirm this. Thank you very much. Looking forward to toy arround with it in the next days.
